# Generated by Django 3.2.8 on 2021-10-20 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', models.CharField(max_length=120)),
                ('plot_num', models.CharField(max_length=120)),
                ('area', models.CharField(max_length=50)),
                ('is_alloted', models.BooleanField()),
            ],
        ),
    ]
