# Generated by Django 3.2.8 on 2021-11-05 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name_plural': 'properties'},
        ),
        migrations.AddField(
            model_name='property',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='property/files/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='is_alloted',
            field=models.BooleanField(default=False),
        ),
    ]
