# Generated by Django 3.2.8 on 2021-11-06 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_auto_20211106_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='C:\\Users\\Usama\\Desktop\\property-managment\\media'),
        ),
    ]
