# Generated by Django 3.2.8 on 2021-11-09 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_property_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='user',
        ),
    ]
